
import type { Subject, Question } from './types';

export const subjects: Subject[] = [
  {
    id: 'applied-mathematics',
    name: 'Applied Mathematics',
    description: 'Fundamental concepts of mathematics applied in engineering.',
    topics: ['Algebra', 'Trigonometry', 'Calculus', 'Differential Equations', 'Probability'],
    image: 'https://placehold.co/600x400.png',
  },
  {
    id: 'basic-electronics',
    name: 'Basic Electronics',
    description: 'Introduction to electronic devices and circuits.',
    topics: ['Semiconductors', 'Diodes', 'Transistors', 'Operational Amplifiers', 'Digital Logic'],
    image: 'https://placehold.co/600x400.png',
  },
  {
    id: 'programming-in-c',
    name: 'Programming in C',
    description: 'Learn the fundamentals of programming using the C language.',
    topics: ['Variables & Data Types', 'Control Structures', 'Functions', 'Arrays & Pointers', 'File Handling'],
    image: 'https://placehold.co/600x400.png',
  },
  {
    id: 'management',
    name: 'Management (22509)',
    description: 'Principles and practices of management for technical professionals and entrepreneurs.',
    topics: ['Introduction to Management Concepts', 'Planning and Organizing', 'Directing and Controlling', 'Safety Management', 'Entrepreneurship', 'Industrial Acts and Labour Laws'],
    image: 'https://placehold.co/600x400.png',
  },
];

export const questions: Question[] = [
  // Applied Mathematics
  {
    id: 'am_q1',
    subjectId: 'applied-mathematics',
    topic: 'Algebra',
    text: 'What is the value of x if 2x + 5 = 15?',
    options: ['3', '5', '7', '10'],
    correctAnswer: '5',
    explanation: '2x = 15 - 5 => 2x = 10 => x = 10/2 => x = 5.',
  },
  {
    id: 'am_q2',
    subjectId: 'applied-mathematics',
    topic: 'Trigonometry',
    text: 'What is sin(90 degrees)?',
    options: ['0', '0.5', '1', 'undefined'],
    correctAnswer: '1',
  },
  {
    id: 'am_q3',
    subjectId: 'applied-mathematics',
    topic: 'Calculus',
    text: 'What is the derivative of x^2?',
    options: ['x', '2x', 'x^2/2', '2'],
    correctAnswer: '2x',
  },
  // Basic Electronics
  {
    id: 'be_q1',
    subjectId: 'basic-electronics',
    topic: 'Semiconductors',
    text: 'Which of these is a semiconductor?',
    options: ['Copper', 'Silicon', 'Glass', 'Rubber'],
    correctAnswer: 'Silicon',
    explanation: 'Silicon is a widely used semiconductor material.',
  },
  {
    id: 'be_q2',
    subjectId: 'basic-electronics',
    topic: 'Diodes',
    text: 'A diode allows current to flow in how many directions?',
    options: ['One', 'Two', 'Zero', 'Four'],
    correctAnswer: 'One',
  },
  // Programming in C
  {
    id: 'pc_q1',
    subjectId: 'programming-in-c',
    topic: 'Variables & Data Types',
    text: 'Which keyword is used to define a constant in C?',
    options: ['const', 'let', 'final', 'static'],
    correctAnswer: 'const',
  },
  {
    id: 'pc_q2',
    subjectId: 'programming-in-c',
    topic: 'Control Structures',
    text: 'What is the output of `printf("%d", 10 > 5);`?',
    options: ['10', '5', '1', '0'],
    correctAnswer: '1',
    explanation: 'In C, true conditions evaluate to 1.',
  },
  // Management (22509) - Questions from user
  {
    id: 'mgt_q1',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Indian factory act come in to force on ----------',
    options: ['1st May 1960', '1st April 1949', '15th August 1947', '26th January 1950'],
    correctAnswer: '1st April 1949',
  },
  {
    id: 'mgt_q2',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'As per Indian factory act, The person who has control over the affairs of factory is known as -------',
    options: ['Employee', 'Worker', 'Occupier', 'None of the above'],
    correctAnswer: 'Occupier',
  },
  {
    id: 'mgt_q3',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Section 27 under the Industrial dispute act is about ........',
    options: ['Manufacturing process', 'Penalty for instigation', 'Occupier', 'None of the above'],
    correctAnswer: 'Penalty for instigation',
  },
  {
    id: 'mgt_q4',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'As per Indian Factory act, Employer has to provide canteen facility, if there are ---- number of employees.',
    options: ['50', '100', '200', '250'],
    correctAnswer: '250',
  },
  {
    id: 'mgt_q5',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------------- section of Industrial Dispute act covers the topic penalty for instigation.',
    options: ['Section 7', 'Section 27', 'Section 5', 'None of the above'],
    correctAnswer: 'Section 27',
  },
  {
    id: 'mgt_q6',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '-- is not statuary welfare facility under Factory act',
    options: ['Canteen', 'Medical', 'Transport', 'None of the above'],
    correctAnswer: 'Transport',
  },
  {
    id: 'mgt_q7',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Bhopal gas tragedy led to an amendment under ---- legislation',
    options: ['Indian Safety act', 'Indian boiler act', 'Indian wage act', 'None of the above'],
    correctAnswer: 'None of the above',
  },
  {
    id: 'mgt_q8',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Arrangements of drinking water is mentioned under------ section of Factory act',
    options: ['15', '11', '10', '18'],
    correctAnswer: '18',
  },
  {
    id: 'mgt_q9',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'For contravention of provisions of factories act , the occupier shall liable for punishment up to .-------',
    options: ['Fine of Rs 10000', 'Fine of Rs 100000', 'Fine of Rs 200000', 'None of the above'],
    correctAnswer: 'None of the above',
  },
  {
    id: 'mgt_q10',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The license fee can be paid to get license for a factory maximum up to --------',
    options: ['One year', 'Two year', 'Five Year', 'Three year'],
    correctAnswer: 'Five Year',
  },
  // Batch 2 for Management
  {
    id: 'mgt_q11',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The occupier of a factory is required to send written notice to the Chief Inspector of Factories at least ------- days before he begins to occupy the premises as factory.',
    options: ['7', '15', '10', '30'],
    correctAnswer: '15',
  },
  {
    id: 'mgt_q12',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'As per the Factories Act, 1948 any engine, motor or other appliance which generates or otherwise provides power is termed as --------------',
    options: ['Prime Mover', 'Machinery', 'Equipment', 'All of the Above'],
    correctAnswer: 'Prime Mover',
  },
  {
    id: 'mgt_q13',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'As per section 16 of the Factory Act, 1948 the minimum space to be allocated to each worker employed in the factory is ---------------',
    options: ['12.2 cu.met', '13.2 cu.met', '4.2 cu.met', '15.2 cu.met'],
    correctAnswer: '4.2 cu.met', // Note: This seems low. The Factories Act often specifies values like 9.9 or 14.2 cubic meters depending on when the factory was built. Assuming 4.2 is from the user's source.
  },
  {
    id: 'mgt_q14',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'An adult worker is allowed to work for -------- hours in a week.',
    options: ['35', '48', '40', '45'],
    correctAnswer: '48',
  },
  {
    id: 'mgt_q15',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------- is not an essential element of a factory',
    options: ['There must be a premises', 'There must be manufacturing process being carried on at the premises', 'There must be ten or more workers where the manufacturing process is being carried on with the aid of power', 'There must be an electronic data processing unit installed'],
    correctAnswer: 'There must be an electronic data processing unit installed',
  },
  {
    id: 'mgt_q16',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Section 2 (m) of the Factory Act 1948 Says about --',
    options: ['Factory', 'Manufacturing Process', 'Workers', 'All of the Above'],
    correctAnswer: 'Manufacturing Process',
  },
  {
    id: 'mgt_q17',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Crèche is to be provided if______ or more lady employees are engaged',
    options: ['15', '25', '30', '40'],
    correctAnswer: '30',
  },
  {
    id: 'mgt_q18',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The maximum daily hours of work in a day with normal wage allowed in factories is -----------',
    options: ['8', '9', '10', '11'],
    correctAnswer: '9',
  },
  {
    id: 'mgt_q19',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '--------- is the chairman of Site Appraisal Committees',
    options: ['The Chief Inspector of the State', 'The Inspector of The District', 'Occupier', 'None of the above'],
    correctAnswer: 'The Chief Inspector of the State',
  },
  {
    id: 'mgt_q20',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------- authority enforces the Factory Act 1948',
    options: ['The Heavy Industries Department of Central Government', 'Human Resources Department', 'The Labour Department of the State Government', 'All of the Above'],
    correctAnswer: 'The Labour Department of the State Government',
  },
  // Batch 3 for Management
  {
    id: 'mgt_q21',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '--- year did the Industrial Dispute act come into operation.',
    options: ['1960', '1947', '2019', '1965'],
    correctAnswer: '1947',
  },
  {
    id: 'mgt_q22',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The industrial peace is secured through voluntary _______ and compulsory ________',
    options: ['Compromise and Arbitration', 'Adjudication and Arbitration', 'Work Committee and Industrial Tribunal', 'Negotiation and Adjudication'],
    correctAnswer: 'Negotiation and Adjudication',
  },
  {
    id: 'mgt_q23',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------- legislation there is a provision called ‘protected workmen’.',
    options: ['Trade Unions Act, 1926', 'Industrial Employment (Standing Orders) Act, 1946', 'Industrial Disputes Act, 1947', 'Factories Act, 1948'],
    correctAnswer: 'Industrial Disputes Act, 1947',
  },
  {
    id: 'mgt_q24',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Grievance Handing Machinery is given in ---------',
    options: ['Industrial Dispute Act', 'Indian factory act', 'Minimum Wages act', 'All of the Above'],
    correctAnswer: 'Industrial Dispute Act',
  },
  {
    id: 'mgt_q25',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'To provide compensation to workmen in cases of Lay-off, retrenchment and closure is a provision of ............... Act.',
    options: ['Factory Act', 'Industrial Dispute', 'Workmen Compensation', 'None of the above'],
    correctAnswer: 'Industrial Dispute',
  },
  {
    id: 'mgt_q26',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '-------- is a machinery for the settlement of Industrial Disputes in India',
    options: ['National Commission on Labour', 'Wage Board', 'Industrial Tribunal', 'Standing Labour Committee'],
    correctAnswer: 'Industrial Tribunal',
  },
  {
    id: 'mgt_q27',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------- machinery has been mentioned in the Industrial Dispute act accountable for the speedy and amicable settlement of industrial disputes',
    options: ['Adjudication', 'Conciliation', 'Arbitration', 'Appropriate government'],
    correctAnswer: 'Conciliation',
  },
  {
    id: 'mgt_q28',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '________ means an interim or a final determination of any industrial dispute or of any question relating there to by any labour court.',
    options: ['Banking Company', 'Conciliation Proceeding', 'Closure', 'Award'],
    correctAnswer: 'Award',
  },
  {
    id: 'mgt_q29',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Industrial Dispute means, Dispute between -----',
    options: ['Employer and workmen', 'Workmen and workmen', 'Employer and Employer', 'All of the Above'],
    correctAnswer: 'All of the Above',
  },
  {
    id: 'mgt_q30',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The ------- authorities are set up for settling the industrial Dispute.',
    options: ['Labor court', 'Industrial Tribunal', 'Conciliation Board', 'All of the Above'],
    correctAnswer: 'All of the Above',
  },
];

export const getQuestionsBySubject = (subjectId: string): Question[] => {
  return questions.filter(q => q.subjectId === subjectId);
};

export const getSubjectById = (subjectId: string): Subject | undefined => {
  return subjects.find(s => s.id === subjectId);
};


    