
import type { Subject, Question } from './types';

export const subjects: Subject[] = [
  {
    id: 'applied-mathematics',
    name: 'Applied Mathematics',
    description: 'Fundamental concepts of mathematics applied in engineering.',
    topics: ['Algebra', 'Trigonometry', 'Calculus', 'Differential Equations', 'Probability'],
    image: 'https://placehold.co/600x400.png',
  },
  {
    id: 'basic-electronics',
    name: 'Basic Electronics',
    description: 'Introduction to electronic devices and circuits.',
    topics: ['Semiconductors', 'Diodes', 'Transistors', 'Operational Amplifiers', 'Digital Logic'],
    image: 'https://placehold.co/600x400.png',
  },
  {
    id: 'programming-in-c',
    name: 'Programming in C',
    description: 'Learn the fundamentals of programming using the C language.',
    topics: ['Variables & Data Types', 'Control Structures', 'Functions', 'Arrays & Pointers', 'File Handling'],
    image: 'https://placehold.co/600x400.png',
  },
  {
    id: 'management',
    name: 'Management (22509)',
    description: 'Principles and practices of management for technical professionals and entrepreneurs.',
    topics: ['Introduction to Management Concepts', 'Planning and Organizing', 'Directing and Controlling', 'Safety Management', 'Entrepreneurship', 'Industrial Acts and Labour Laws'],
    image: 'https://placehold.co/600x400.png',
  },
];

export const questions: Question[] = [
  // Applied Mathematics
  {
    id: 'am_q1',
    subjectId: 'applied-mathematics',
    topic: 'Algebra',
    text: 'What is the value of x if 2x + 5 = 15?',
    options: ['3', '5', '7', '10'],
    correctAnswer: '5',
    explanation: '2x = 15 - 5 => 2x = 10 => x = 10/2 => x = 5.',
  },
  {
    id: 'am_q2',
    subjectId: 'applied-mathematics',
    topic: 'Trigonometry',
    text: 'What is sin(90 degrees)?',
    options: ['0', '0.5', '1', 'undefined'],
    correctAnswer: '1',
  },
  {
    id: 'am_q3',
    subjectId: 'applied-mathematics',
    topic: 'Calculus',
    text: 'What is the derivative of x^2?',
    options: ['x', '2x', 'x^2/2', '2'],
    correctAnswer: '2x',
  },
  // Basic Electronics
  {
    id: 'be_q1',
    subjectId: 'basic-electronics',
    topic: 'Semiconductors',
    text: 'Which of these is a semiconductor?',
    options: ['Copper', 'Silicon', 'Glass', 'Rubber'],
    correctAnswer: 'Silicon',
    explanation: 'Silicon is a widely used semiconductor material.',
  },
  {
    id: 'be_q2',
    subjectId: 'basic-electronics',
    topic: 'Diodes',
    text: 'A diode allows current to flow in how many directions?',
    options: ['One', 'Two', 'Zero', 'Four'],
    correctAnswer: 'One',
  },
  // Programming in C
  {
    id: 'pc_q1',
    subjectId: 'programming-in-c',
    topic: 'Variables & Data Types',
    text: 'Which keyword is used to define a constant in C?',
    options: ['const', 'let', 'final', 'static'],
    correctAnswer: 'const',
  },
  {
    id: 'pc_q2',
    subjectId: 'programming-in-c',
    topic: 'Control Structures',
    text: 'What is the output of `printf("%d", 10 > 5);`?',
    options: ['10', '5', '1', '0'],
    correctAnswer: '1',
    explanation: 'In C, true conditions evaluate to 1.',
  },
  // Management (22509) - Questions from user
  {
    id: 'mgt_q1',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Indian factory act come in to force on ----------',
    options: ['1st May 1960', '1st April 1949', '15th August 1947', '26th January 1950'],
    correctAnswer: '1st April 1949',
  },
  {
    id: 'mgt_q2',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'As per Indian factory act, The person who has control over the affairs of factory is known as -------',
    options: ['Employee', 'Worker', 'Occupier', 'None of the above'],
    correctAnswer: 'Occupier',
  },
  {
    id: 'mgt_q3',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Section 27 under the Industrial dispute act is about ........',
    options: ['Manufacturing process', 'Penalty for instigation', 'Occupier', 'None of the above'],
    correctAnswer: 'Penalty for instigation',
  },
  {
    id: 'mgt_q4',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'As per Indian Factory act, Employer has to provide canteen facility, if there are ---- number of employees.',
    options: ['50', '100', '200', '250'],
    correctAnswer: '250',
  },
  {
    id: 'mgt_q5',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------------- section of Industrial Dispute act covers the topic penalty for instigation.',
    options: ['Section 7', 'Section 27', 'Section 5', 'None of the above'],
    correctAnswer: 'Section 27',
  },
  {
    id: 'mgt_q6',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '-- is not statuary welfare facility under Factory act',
    options: ['Canteen', 'Medical', 'Transport', 'None of the above'],
    correctAnswer: 'Transport',
  },
  {
    id: 'mgt_q7',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Bhopal gas tragedy led to an amendment under ---- legislation',
    options: ['Indian Safety act', 'Indian boiler act', 'Indian wage act', 'None of the above'],
    correctAnswer: 'None of the above',
  },
  {
    id: 'mgt_q8',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Arrangements of drinking water is mentioned under------ section of Factory act',
    options: ['15', '11', '10', '18'],
    correctAnswer: '18',
  },
  {
    id: 'mgt_q9',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'For contravention of provisions of factories act , the occupier shall liable for punishment up to .-------',
    options: ['Fine of Rs 10000', 'Fine of Rs 100000', 'Fine of Rs 200000', 'None of the above'],
    correctAnswer: 'None of the above',
  },
  {
    id: 'mgt_q10',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The license fee can be paid to get license for a factory maximum up to --------',
    options: ['One year', 'Two year', 'Five Year', 'Three year'],
    correctAnswer: 'Five Year',
  },
  // Batch 2 for Management
  {
    id: 'mgt_q11',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The occupier of a factory is required to send written notice to the Chief Inspector of Factories at least ------- days before he begins to occupy the premises as factory.',
    options: ['7', '15', '10', '30'],
    correctAnswer: '15',
  },
  {
    id: 'mgt_q12',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'As per the Factories Act, 1948 any engine, motor or other appliance which generates or otherwise provides power is termed as --------------',
    options: ['Prime Mover', 'Machinery', 'Equipment', 'All of the Above'],
    correctAnswer: 'Prime Mover',
  },
  {
    id: 'mgt_q13',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'As per section 16 of the Factory Act, 1948 the minimum space to be allocated to each worker employed in the factory is ---------------',
    options: ['12.2 cu.met', '13.2 cu.met', '4.2 cu.met', '15.2 cu.met'],
    correctAnswer: '4.2 cu.met',
  },
  {
    id: 'mgt_q14',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'An adult worker is allowed to work for -------- hours in a week.',
    options: ['35', '48', '40', '45'],
    correctAnswer: '48',
  },
  {
    id: 'mgt_q15',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------- is not an essential element of a factory',
    options: ['There must be a premises', 'There must be manufacturing process being carried on at the premises', 'There must be ten or more workers where the manufacturing process is being carried on with the aid of power', 'There must be an electronic data processing unit installed'],
    correctAnswer: 'There must be an electronic data processing unit installed',
  },
  {
    id: 'mgt_q16',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Section 2 (m) of the Factory Act 1948 Says about --',
    options: ['Factory', 'Manufacturing Process', 'Workers', 'All of the Above'],
    correctAnswer: 'Manufacturing Process',
  },
  {
    id: 'mgt_q17',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Crèche is to be provided if______ or more lady employees are engaged',
    options: ['15', '25', '30', '40'],
    correctAnswer: '30',
  },
  {
    id: 'mgt_q18',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The maximum daily hours of work in a day with normal wage allowed in factories is -----------',
    options: ['8', '9', '10', '11'],
    correctAnswer: '9',
  },
  {
    id: 'mgt_q19',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '--------- is the chairman of Site Appraisal Committees',
    options: ['The Chief Inspector of the State', 'The Inspector of The District', 'Occupier', 'None of the above'],
    correctAnswer: 'The Chief Inspector of the State',
  },
  {
    id: 'mgt_q20',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------- authority enforces the Factory Act 1948',
    options: ['The Heavy Industries Department of Central Government', 'Human Resources Department', 'The Labour Department of the State Government', 'All of the Above'],
    correctAnswer: 'The Labour Department of the State Government',
  },
  // Batch 3 for Management
  {
    id: 'mgt_q21',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '--- year did the Industrial Dispute act come into operation.',
    options: ['1960', '1947', '2019', '1965'],
    correctAnswer: '1947',
  },
  {
    id: 'mgt_q22',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The industrial peace is secured through voluntary _______ and compulsory ________',
    options: ['Compromise and Arbitration', 'Adjudication and Arbitration', 'Work Committee and Industrial Tribunal', 'Negotiation and Adjudication'],
    correctAnswer: 'Negotiation and Adjudication',
  },
  {
    id: 'mgt_q23',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------- legislation there is a provision called ‘protected workmen’.',
    options: ['Trade Unions Act, 1926', 'Industrial Employment (Standing Orders) Act, 1946', 'Industrial Disputes Act, 1947', 'Factories Act, 1948'],
    correctAnswer: 'Industrial Disputes Act, 1947',
  },
  {
    id: 'mgt_q24',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Grievance Handing Machinery is given in ---------',
    options: ['Industrial Dispute Act', 'Indian factory act', 'Minimum Wages act', 'All of the Above'],
    correctAnswer: 'Industrial Dispute Act',
  },
  {
    id: 'mgt_q25',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'To provide compensation to workmen in cases of Lay-off, retrenchment and closure is a provision of ............... Act.',
    options: ['Factory Act', 'Industrial Dispute', 'Workmen Compensation', 'None of the above'],
    correctAnswer: 'Industrial Dispute',
  },
  {
    id: 'mgt_q26',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '-------- is a machinery for the settlement of Industrial Disputes in India',
    options: ['National Commission on Labour', 'Wage Board', 'Industrial Tribunal', 'Standing Labour Committee'],
    correctAnswer: 'Industrial Tribunal',
  },
  {
    id: 'mgt_q27',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------- machinery has been mentioned in the Industrial Dispute act accountable for the speedy and amicable settlement of industrial disputes',
    options: ['Adjudication', 'Conciliation', 'Arbitration', 'Appropriate government'],
    correctAnswer: 'Conciliation',
  },
  {
    id: 'mgt_q28',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '________ means an interim or a final determination of any industrial dispute or of any question relating there to by any labour court.',
    options: ['Banking Company', 'Conciliation Proceeding', 'Closure', 'Award'],
    correctAnswer: 'Award',
  },
  {
    id: 'mgt_q29',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Industrial Dispute means, Dispute between -----',
    options: ['Employer and workmen', 'Workmen and workmen', 'Employer and Employer', 'All of the Above'],
    correctAnswer: 'All of the Above',
  },
  {
    id: 'mgt_q30',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The ------- authorities are set up for settling the industrial Dispute.',
    options: ['Labor court', 'Industrial Tribunal', 'Conciliation Board', 'All of the Above'],
    correctAnswer: 'All of the Above',
  },
  // Batch 4 for Management
  {
    id: 'mgt_q31',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'An arbitrator is appointed by ------------',
    options: ['Employer', 'Lawyer', 'Government', 'All of the Above'],
    correctAnswer: 'Government',
  },
  {
    id: 'mgt_q32',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '‘Award’ under Industrial Disputes Act, 1947 is-------',
    options: ['Interim determination of industrial dispute', 'Final determination of industrial dispute', 'Arbitration award under Section 10A', 'Both A & B'],
    correctAnswer: 'Both A & B',
  },
  {
    id: 'mgt_q33',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Under the Industrial Disputes Act, ------- is not be considered as an industrial dispute',
    options: ['When employer fails to keep his verbal promises', 'When closure is a pretence', 'When demand made for alteration of conditions of service of employees in a cooperative society', 'When the lock-out is in disguise of closure'],
    correctAnswer: 'When demand made for alteration of conditions of service of employees in a cooperative society',
  },
  {
    id: 'mgt_q34',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The ongoing globalization in India requires drastic changes under --------- of the labour legislation.',
    options: ['The Factory Act', 'The Employees’ State Insurance Act', 'The Industrial Disputes Act', 'The Employees’ Provident Funds Act'],
    correctAnswer: 'The Industrial Disputes Act',
  },
  {
    id: 'mgt_q35',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------------- includes any court constituted under any law relating to investigation and settlement of industrial disputes in force in any State',
    options: ['Labour court', 'District court', 'Supreme court', 'None of the above'],
    correctAnswer: 'Labour court',
  },
  {
    id: 'mgt_q36',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '----------- members does a conciliation board consist of as per the appropriate government',
    options: ['Chairman and one member', 'Chairman and 2-4 members', 'Chairman only', 'None of the above'],
    correctAnswer: 'Chairman and 2-4 members',
  },
  {
    id: 'mgt_q37',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'A national tribunal consist of ---- number of person/s to be appointed by the central government.',
    options: ['2', '5', '1', '3'],
    correctAnswer: '1',
  },
  {
    id: 'mgt_q38',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------- is the time period in which all the awards of the arbitration are to be published from the date of its receipt by the appropriate government',
    options: ['15 days', '7 days', '180 days', '30 days'],
    correctAnswer: '30 days',
  },
  {
    id: 'mgt_q39',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'As per section ___ a conciliation proceeding shall be deemed to have commenced on the date on which a strike or lock - out is received by the conciliation officer',
    options: ['22', '20', '18', '19'],
    correctAnswer: '22',
  },
  {
    id: 'mgt_q40',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'No person employed in a public utility service shall go on strike in breach of contract within ____ of giving such a notice.',
    options: ['2 weeks', '6 weeks', '1 week', '4 weeks'],
    correctAnswer: '6 weeks',
  },
  // Batch 5 for Management
  {
    id: 'mgt_q41',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Section ____ of industrial dispute act covers the compensation provided to workers who are in continuous service for not less than one year.',
    options: ['25', '25A', '25-FFF', '26'],
    correctAnswer: '25-FFF',
  },
  {
    id: 'mgt_q42',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'A workmen who is employed in an industrial establishment in the place of another workman whose name is borne on the muster rolls of the establishment is -------------',
    options: ['Temporary workmen', 'Permanent workmen', 'Badali workman', 'All of the above'],
    correctAnswer: 'Badali workman',
  },
  {
    id: 'mgt_q43',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '"Dependent" means ------- relatives of a deceased workman,',
    options: ['Widow', 'Minor legitimate son', 'Unmarried legitimate daughter', 'All of the above'],
    correctAnswer: 'All of the above',
  },
  {
    id: 'mgt_q44',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'A person named as Minor who has not attained the age of ----- years',
    options: ['21', '18', '20', 'None of the above'],
    correctAnswer: '18',
  },
  {
    id: 'mgt_q45',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'If death results from the injury, the amount of compensation to the employee equal to',
    options: ['40% monthly wages multiplied by the relevant factor', '150% monthly wages multiplied by the relevant factor', '100% monthly wages multiplied by the relevant factor', 'None of the above'],
    correctAnswer: '40% monthly wages multiplied by the relevant factor',
  },
  {
    id: 'mgt_q46',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Minimum rates of wages may be fixed by -----',
    options: ['Hour', 'Day', 'Month', 'All of the above'],
    correctAnswer: 'All of the above',
  },
  {
    id: 'mgt_q47',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'If workmen loss of both hands or amputation at higher sites then he /she will get compensation ----- percentage of loss of earning capacity',
    options: ['25', '100', '50', 'None of the above'],
    correctAnswer: '100',
  },
  {
    id: 'mgt_q48',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'If workmen have permanent total disablement, he /she will get compensation amount ----- percentage of monthly wages.',
    options: ['50', '25', '100', 'None of the above'],
    correctAnswer: '50',
  },
  {
    id: 'mgt_q49',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'A workmen have amputation through shoulder joint, then he/she will get compensation ----- Percentage of loss of earning capacity.',
    options: ['10', '50', '70', '90'],
    correctAnswer: '90',
  },
  {
    id: 'mgt_q50',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'A workmen have loss of both eyes, then He/She will get compensation ------ Percentage of loss of earning capacity',
    options: ['30', '50', '40', '100'],
    correctAnswer: '50',
  },
];

export const getQuestionsBySubject = (subjectId: string): Question[] => {
  return questions.filter(q => q.subjectId === subjectId);
};

export const getSubjectById = (subjectId: string): Subject | undefined => {
  return subjects.find(s => s.id === subjectId);
};


    
