
import type { Subject, Question } from './types';

export const DEFAULT_BATCH_SIZE = 70;

export const subjects: Subject[] = [
  {
    id: 'applied-mathematics',
    name: 'Applied Mathematics',
    description: 'Fundamental concepts of mathematics applied in engineering.',
    topics: ['Algebra', 'Trigonometry', 'Calculus', 'Differential Equations', 'Probability'],
    image: 'https://placehold.co/600x400.png',
  },
  {
    id: 'basic-electronics',
    name: 'Basic Electronics',
    description: 'Introduction to electronic devices and circuits.',
    topics: ['Semiconductors', 'Diodes', 'Transistors', 'Operational Amplifiers', 'Digital Logic'],
    image: 'https://placehold.co/600x400.png',
  },
  {
    id: 'programming-in-c',
    name: 'Programming in C',
    description: 'Learn the fundamentals of programming using the C language.',
    topics: ['Variables & Data Types', 'Control Structures', 'Functions', 'Arrays & Pointers', 'File Handling'],
    image: 'https://placehold.co/600x400.png',
  },
  {
    id: 'management',
    name: 'Management (22509)',
    description: 'Principles and practices of management for technical professionals and entrepreneurs.',
    topics: ['Introduction to Management Concepts', 'Planning and Organizing', 'Directing and Controlling', 'Safety Management', 'Entrepreneurship', 'Industrial Acts and Labour Laws', 'Compensation and Wage Policies'],
    image: 'https://placehold.co/600x400.png',
  },
];

export const questions: Question[] = [
  // Applied Mathematics
  {
    id: 'am_q1',
    subjectId: 'applied-mathematics',
    topic: 'Algebra',
    text: 'What is the value of x if 2x + 5 = 15?',
    options: ['3', '5', '7', '10'],
    correctAnswer: '5',
    explanation: '2x = 15 - 5 => 2x = 10 => x = 10/2 => x = 5.',
  },
  {
    id: 'am_q2',
    subjectId: 'applied-mathematics',
    topic: 'Trigonometry',
    text: 'What is sin(90 degrees)?',
    options: ['0', '0.5', '1', 'undefined'],
    correctAnswer: '1',
  },
  {
    id: 'am_q3',
    subjectId: 'applied-mathematics',
    topic: 'Calculus',
    text: 'What is the derivative of x^2?',
    options: ['x', '2x', 'x^2/2', '2'],
    correctAnswer: '2x',
  },
  // Basic Electronics
  {
    id: 'be_q1',
    subjectId: 'basic-electronics',
    topic: 'Semiconductors',
    text: 'Which of these is a semiconductor?',
    options: ['Copper', 'Silicon', 'Glass', 'Rubber'],
    correctAnswer: 'Silicon',
    explanation: 'Silicon is a widely used semiconductor material.',
  },
  {
    id: 'be_q2',
    subjectId: 'basic-electronics',
    topic: 'Diodes',
    text: 'A diode allows current to flow in how many directions?',
    options: ['One', 'Two', 'Zero', 'Four'],
    correctAnswer: 'One',
  },
  // Programming in C
  {
    id: 'pc_q1',
    subjectId: 'programming-in-c',
    topic: 'Variables & Data Types',
    text: 'Which keyword is used to define a constant in C?',
    options: ['const', 'let', 'final', 'static'],
    correctAnswer: 'const',
  },
  {
    id: 'pc_q2',
    subjectId: 'programming-in-c',
    topic: 'Control Structures',
    text: 'What is the output of `printf("%d", 10 > 5);`?',
    options: ['10', '5', '1', '0'],
    correctAnswer: '1',
    explanation: 'In C, true conditions evaluate to 1.',
  },

  // Management (22509) Questions
  // Batch 1 (Questions 1-70)
  // Topic: Industrial Acts and Labour Laws (Questions 1-50 from this topic in this batch)
  {
    id: 'mgt_q1',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Indian factory act come in to force on ----------',
    options: ['1st May 1960', '1st April 1949', '15th August 1947', '26th January 1950'],
    correctAnswer: '1st April 1949',
  },
  {
    id: 'mgt_q2',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'As per Indian factory act, The person who has control over the affairs of factory is known as -------',
    options: ['Employee', 'Worker', 'Occupier', 'None of the above'],
    correctAnswer: 'Occupier',
  },
  {
    id: 'mgt_q3',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Section 27 under the Industrial dispute act is about ........',
    options: ['Manufacturing process', 'Penalty for instigation', 'Occupier', 'None of the above'],
    correctAnswer: 'Penalty for instigation',
  },
  {
    id: 'mgt_q4',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'As per Indian Factory act, Employer has to provide canteen facility, if there are ---- number of employees.',
    options: ['50', '100', '200', '250'],
    correctAnswer: '250',
  },
  {
    id: 'mgt_q5',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------------- section of Industrial Dispute act covers the topic penalty for instigation.',
    options: ['Section 7', 'Section 27', 'Section 5', 'None of the above'],
    correctAnswer: 'Section 27',
  },
  {
    id: 'mgt_q6',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '-- is not statuary welfare facility under Factory act',
    options: ['Canteen', 'Medical', 'Transport', 'None of the above'],
    correctAnswer: 'Transport',
  },
  {
    id: 'mgt_q7',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Bhopal gas tragedy led to an amendment under ---- legislation',
    options: ['Indian Safety act', 'Indian boiler act', 'Indian wage act', 'None of the above'],
    correctAnswer: 'None of the above',
  },
  {
    id: 'mgt_q8',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Arrangements of drinking water is mentioned under------ section of Factory act',
    options: ['15', '11', '10', '18'],
    correctAnswer: '18',
  },
  {
    id: 'mgt_q9',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'For contravention of provisions of factories act , the occupier shall liable for punishment up to .-------',
    options: ['Fine of Rs 10000', 'Fine of Rs 100000', 'Fine of Rs 200000', 'None of the above'],
    correctAnswer: 'None of the above',
  },
  {
    id: 'mgt_q10',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The license fee can be paid to get license for a factory maximum up to --------',
    options: ['One year', 'Two year', 'Five Year', 'Three year'],
    correctAnswer: 'Five Year',
  },
  {
    id: 'mgt_q11',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The occupier of a factory is required to send written notice to the Chief Inspector of Factories at least ------- days before he begins to occupy the premises as factory.',
    options: ['7', '15', '10', '30'],
    correctAnswer: '15',
  },
  {
    id: 'mgt_q12',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'As per the Factories Act, 1948 any engine, motor or other appliance which generates or otherwise provides power is termed as --------------',
    options: ['Prime Mover', 'Machinery', 'Equipment', 'All of the Above'],
    correctAnswer: 'Prime Mover',
  },
  {
    id: 'mgt_q13',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'As per section 16 of the Factory Act, 1948 the minimum space to be allocated to each worker employed in the factory is ---------------',
    options: ['12.2 cu.met', '13.2 cu.met', '4.2 cu.met', '15.2 cu.met'],
    correctAnswer: '4.2 cu.met',
  },
  {
    id: 'mgt_q14',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'An adult worker is allowed to work for -------- hours in a week.',
    options: ['35', '48', '40', '45'],
    correctAnswer: '48',
  },
  {
    id: 'mgt_q15',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------- is not an essential element of a factory',
    options: ['There must be a premises', 'There must be manufacturing process being carried on at the premises', 'There must be ten or more workers where the manufacturing process is being carried on with the aid of power', 'There must be an electronic data processing unit installed'],
    correctAnswer: 'There must be an electronic data processing unit installed',
  },
  {
    id: 'mgt_q16',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Section 2 (m) of the Factory Act 1948 Says about --',
    options: ['Factory', 'Manufacturing Process', 'Workers', 'All of the Above'],
    correctAnswer: 'Manufacturing Process',
  },
  {
    id: 'mgt_q17',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Crèche is to be provided if______ or more lady employees are engaged',
    options: ['15', '25', '30', '40'],
    correctAnswer: '30',
  },
  {
    id: 'mgt_q18',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The maximum daily hours of work in a day with normal wage allowed in factories is -----------',
    options: ['8', '9', '10', '11'],
    correctAnswer: '9',
  },
  {
    id: 'mgt_q19',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '--------- is the chairman of Site Appraisal Committees',
    options: ['The Chief Inspector of the State', 'The Inspector of The District', 'Occupier', 'None of the above'],
    correctAnswer: 'The Chief Inspector of the State',
  },
  {
    id: 'mgt_q20',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------- authority enforces the Factory Act 1948',
    options: ['The Heavy Industries Department of Central Government', 'Human Resources Department', 'The Labour Department of the State Government', 'All of the Above'],
    correctAnswer: 'The Labour Department of the State Government',
  },
  {
    id: 'mgt_q21',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '--- year did the Industrial Dispute act come into operation.',
    options: ['1960', '1947', '2019', '1965'],
    correctAnswer: '1947',
  },
  {
    id: 'mgt_q22',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The industrial peace is secured through voluntary _______ and compulsory ________',
    options: ['Compromise and Arbitration', 'Adjudication and Arbitration', 'Work Committee and Industrial Tribunal', 'Negotiation and Adjudication'],
    correctAnswer: 'Negotiation and Adjudication',
  },
  {
    id: 'mgt_q23',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------- legislation there is a provision called ‘protected workmen’.',
    options: ['Trade Unions Act, 1926', 'Industrial Employment (Standing Orders) Act, 1946', 'Industrial Disputes Act, 1947', 'Factories Act, 1948'],
    correctAnswer: 'Industrial Disputes Act, 1947',
  },
  {
    id: 'mgt_q24',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Grievance Handing Machinery is given in ---------',
    options: ['Industrial Dispute Act', 'Indian factory act', 'Minimum Wages act', 'All of the Above'],
    correctAnswer: 'Industrial Dispute Act',
  },
  {
    id: 'mgt_q25',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'To provide compensation to workmen in cases of Lay-off, retrenchment and closure is a provision of ............... Act.',
    options: ['Factory Act', 'Industrial Dispute', 'Workmen Compensation', 'None of the above'],
    correctAnswer: 'Industrial Dispute',
  },
  {
    id: 'mgt_q26',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '-------- is a machinery for the settlement of Industrial Disputes in India',
    options: ['National Commission on Labour', 'Wage Board', 'Industrial Tribunal', 'Standing Labour Committee'],
    correctAnswer: 'Industrial Tribunal',
  },
  {
    id: 'mgt_q27',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------- machinery has been mentioned in the Industrial Dispute act accountable for the speedy and amicable settlement of industrial disputes',
    options: ['Adjudication', 'Conciliation', 'Arbitration', 'Appropriate government'],
    correctAnswer: 'Conciliation',
  },
  {
    id: 'mgt_q28',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '________ means an interim or a final determination of any industrial dispute or of any question relating there to by any labour court.',
    options: ['Banking Company', 'Conciliation Proceeding', 'Closure', 'Award'],
    correctAnswer: 'Award',
  },
  {
    id: 'mgt_q29',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Industrial Dispute means, Dispute between -----',
    options: ['Employer and workmen', 'Workmen and workmen', 'Employer and Employer', 'All of the Above'],
    correctAnswer: 'All of the Above',
  },
  {
    id: 'mgt_q30',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The ------- authorities are set up for settling the industrial Dispute.',
    options: ['Labor court', 'Industrial Tribunal', 'Conciliation Board', 'All of the Above'],
    correctAnswer: 'All of the Above',
  },
  {
    id: 'mgt_q31',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'An arbitrator is appointed by ------------',
    options: ['Employer', 'Lawyer', 'Government', 'All of the Above'],
    correctAnswer: 'Government',
  },
  {
    id: 'mgt_q32',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '‘Award’ under Industrial Disputes Act, 1947 is-------',
    options: ['Interim determination of industrial dispute', 'Final determination of industrial dispute', 'Arbitration award under Section 10A', 'Both A & B'],
    correctAnswer: 'Both A & B',
  },
  {
    id: 'mgt_q33',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Under the Industrial Disputes Act, ------- is not be considered as an industrial dispute',
    options: ['When employer fails to keep his verbal promises', 'When closure is a pretence', 'When demand made for alteration of conditions of service of employees in a cooperative society', 'When the lock-out is in disguise of closure'],
    correctAnswer: 'When demand made for alteration of conditions of service of employees in a cooperative society',
  },
  {
    id: 'mgt_q34',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The ongoing globalization in India requires drastic changes under --------- of the labour legislation.',
    options: ['The Factory Act', 'The Employees’ State Insurance Act', 'The Industrial Disputes Act', 'The Employees’ Provident Funds Act'],
    correctAnswer: 'The Industrial Disputes Act',
  },
  {
    id: 'mgt_q35',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------------- includes any court constituted under any law relating to investigation and settlement of industrial disputes in force in any State',
    options: ['Labour court', 'District court', 'Supreme court', 'None of the above'],
    correctAnswer: 'Labour court',
  },
  {
    id: 'mgt_q36',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '----------- members does a conciliation board consist of as per the appropriate government',
    options: ['Chairman and one member', 'Chairman and 2-4 members', 'Chairman only', 'None of the above'],
    correctAnswer: 'Chairman and 2-4 members',
  },
  {
    id: 'mgt_q37',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'A national tribunal consist of ---- number of person/s to be appointed by the central government.',
    options: ['2', '5', '1', '3'],
    correctAnswer: '1',
  },
  {
    id: 'mgt_q38',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------- is the time period in which all the awards of the arbitration are to be published from the date of its receipt by the appropriate government',
    options: ['15 days', '7 days', '180 days', '30 days'],
    correctAnswer: '30 days',
  },
  {
    id: 'mgt_q39',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'As per section ___ a conciliation proceeding shall be deemed to have commenced on the date on which a strike or lock - out is received by the conciliation officer',
    options: ['22', '20', '18', '19'],
    correctAnswer: '22',
  },
  {
    id: 'mgt_q40',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'No person employed in a public utility service shall go on strike in breach of contract within ____ of giving such a notice.',
    options: ['2 weeks', '6 weeks', '1 week', '4 weeks'],
    correctAnswer: '6 weeks',
  },
  {
    id: 'mgt_q41',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Section ____ of industrial dispute act covers the compensation provided to workers who are in continuous service for not less than one year.',
    options: ['25', '25A', '25-FFF', '26'],
    correctAnswer: '25-FFF',
  },
  {
    id: 'mgt_q42',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'A workmen who is employed in an industrial establishment in the place of another workman whose name is borne on the muster rolls of the establishment is -------------',
    options: ['Temporary workmen', 'Permanent workmen', 'Badali workman', 'All of the above'],
    correctAnswer: 'Badali workman',
  },
  {
    id: 'mgt_q43',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '"Dependent" means ------- relatives of a deceased workman,',
    options: ['Widow', 'Minor legitimate son', 'Unmarried legitimate daughter', 'All of the above'],
    correctAnswer: 'All of the above',
  },
  {
    id: 'mgt_q44',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'A person named as Minor who has not attained the age of ----- years',
    options: ['21', '18', '20', 'None of the above'],
    correctAnswer: '18',
  },
  {
    id: 'mgt_q45',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'If death results from the injury, the amount of compensation to the employee equal to',
    options: ['40% monthly wages multiplied by the relevant factor', '150% monthly wages multiplied by the relevant factor', '100% monthly wages multiplied by the relevant factor', 'None of the above'],
    correctAnswer: '40% monthly wages multiplied by the relevant factor',
  },
  {
    id: 'mgt_q46',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Minimum rates of wages may be fixed by -----',
    options: ['Hour', 'Day', 'Month', 'All of the above'],
    correctAnswer: 'All of the above',
  },
  {
    id: 'mgt_q47',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'If workmen loss of both hands or amputation at higher sites then he /she will get compensation ----- percentage of loss of earning capacity',
    options: ['25', '100', '50', 'None of the above'],
    correctAnswer: '100',
  },
  {
    id: 'mgt_q48',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'If workmen have permanent total disablement, he /she will get compensation amount ----- percentage of monthly wages.',
    options: ['50', '25', '100', 'None of the above'],
    correctAnswer: '50',
  },
  {
    id: 'mgt_q49',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'A workmen have amputation through shoulder joint, then he/she will get compensation ----- Percentage of loss of earning capacity.',
    options: ['10', '50', '70', '90'],
    correctAnswer: '90',
  },
  {
    id: 'mgt_q50',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'A workmen have loss of both eyes, then He/She will get compensation ------ Percentage of loss of earning capacity',
    options: ['30', '50', '40', '100'],
    correctAnswer: '50',
  },
  // Topic: Compensation and Wage Policies (Questions 51-60 in this batch)
  {
    id: 'mgt_q51',
    subjectId: 'management',
    topic: 'Compensation and Wage Policies',
    text: 'Basic compensations given to employees as salaries or wages are called -------',
    options: ['Basic pay', 'Wages', 'Salary', 'Variable pay'],
    correctAnswer: 'Basic pay',
  },
  {
    id: 'mgt_q52',
    subjectId: 'management',
    topic: 'Compensation and Wage Policies',
    text: '---------- is the total cash and non-cash payments that you give to an employee in exchange for the work they do for your business.',
    options: ['Salary', 'Compensation', 'Payment', 'All of the above'],
    correctAnswer: 'Compensation',
  },
  {
    id: 'mgt_q53',
    subjectId: 'management',
    topic: 'Compensation and Wage Policies',
    text: '---------- is the initial pay, you give your employees',
    options: ['Wages', 'Salary', 'Compensation', 'Basic Pay'],
    correctAnswer: 'Basic Pay',
  },
  {
    id: 'mgt_q54',
    subjectId: 'management',
    topic: 'Compensation and Wage Policies',
    text: 'Characteristic of a good compensation system is -------',
    options: ['Higher the qualification of worker, higher is compensation', 'Higher the efficiency of worker, higher is compensation', 'Higher the rank of worker, higher is compensation', 'All of the above'],
    correctAnswer: 'All of the above',
  },
  {
    id: 'mgt_q55',
    subjectId: 'management',
    topic: 'Compensation and Wage Policies',
    text: 'Major factors influencing compensation of worker are -----',
    options: ['Skill', 'Effort', 'Working condition', 'All of the above'],
    correctAnswer: 'All of the above',
  },
  {
    id: 'mgt_q56',
    subjectId: 'management',
    topic: 'Compensation and Wage Policies',
    text: 'In graduated time rates system, if basic salary is Rs.2000 and dearness allowance is 150% then total remuneration will be Rs. -----',
    options: ['3000', '5000', '2000', '2150'],
    correctAnswer: '5000',
  },
  {
    id: 'mgt_q57',
    subjectId: 'management',
    topic: 'Compensation and Wage Policies',
    text: 'Most common and usual form of direct compensation paid in organizations is -----',
    options: ['Base pay and benefits', 'Variable pay and benefit', 'Base and variable pay', 'All of the above'],
    correctAnswer: 'Base and variable pay',
  },
  {
    id: 'mgt_q58',
    subjectId: 'management',
    topic: 'Compensation and Wage Policies',
    text: 'An Act to provide for the payment by certain classes of employers to their Employees of compensation for injury by accident ----',
    options: ['Industrial Acts', 'Industrial Dispute Act', 'Workman Compensation Act', 'Minimum Wages Act'],
    correctAnswer: 'Workman Compensation Act',
  },
  {
    id: 'mgt_q59',
    subjectId: 'management',
    topic: 'Compensation and Wage Policies',
    text: '------ means, where the disablement is of a temporary nature, such disablement as reduces the earning capacity of a [employee] in any employment in which he was engaged at the time of the accident resulting in the disablement',
    options: ['Total disablement', 'Partial disablement', 'Major disablement', 'None of the above'],
    correctAnswer: 'Partial disablement',
  },
  {
    id: 'mgt_q60',
    subjectId: 'management',
    topic: 'Compensation and Wage Policies',
    text: '----- is the maximum wage period for the payment of wages',
    options: ['15 days', '21 days', '1 day', '1 month'],
    correctAnswer: '1 month',
  },
  // Mixed Topics for remaining questions in Batch 1 (61-70)
  {
    id: 'mgt_q61',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '-------- deductions is not authorized payment of wages act',
    options: ['Deduction for Fines', 'Deduction for payment of Income tax', 'Deduction for Payment of insurance', 'Deduction for payment of uniform and property'],
    correctAnswer: 'Deduction for payment of uniform and property',
  },
  {
    id: 'mgt_q62',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '-------- of the wages payable is the maximum limit of fine to be imposed on an employee',
    options: ['5%', '1%', '3%', '10%'],
    correctAnswer: '3%',
  },
  {
    id: 'mgt_q63',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Section....... deals with the provisions relating to arrangements for drinking water in factories',
    options: ['18', '12', '9', '7'],
    correctAnswer: '18',
  },
  {
    id: 'mgt_q64',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '-------- means a person who has completed his fourteenth year of age but has not completed his eighteenth year',
    options: ['Adult', 'Adolescent', 'Workmen', 'None of the above'],
    correctAnswer: 'Adolescent',
  },
  {
    id: 'mgt_q65',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '------- means a person who has completed his eighteenth year of age',
    options: ['Minor', 'Adolescent', 'Adult', 'None of the above'],
    correctAnswer: 'Adult',
  },
  {
    id: 'mgt_q66',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: '-------means a person who has not completed his fourteenth year of age',
    options: ['Adult', 'Child', 'Workmen', 'None of the above'],
    correctAnswer: 'Child',
  },
  {
    id: 'mgt_q67',
    subjectId: 'management',
    topic: 'Compensation and Wage Policies',
    text: '------- means all remuneration expressed in terms of money',
    options: ['Salary', 'Wages', 'Mobadla', 'All of the above'],
    correctAnswer: 'Wages',
  },
  {
    id: 'mgt_q68',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'According to the definition of "Week" under the Minimum wage Act, it is a period of 7 days beginning at midnight on______',
    options: ['Sunday', 'Monday', 'Friday', 'Saturday'],
    correctAnswer: 'Saturday',
  },
  {
    id: 'mgt_q69',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The power of inspectors is discussed under Section-------- of the Factories Act, 1948.',
    options: ['9', '10', '11', '12'],
    correctAnswer: '9',
  },
  {
    id: 'mgt_q70',
    subjectId: 'management',
    topic: 'Safety Management',
    text: 'The responsibility for maintenance of employee health and safety is concerned with --------',
    options: ['Employee', 'Employer', 'Government', 'All of the above'],
    correctAnswer: 'All of the above',
  },

  // Management (22509) Questions
  // Batch 2 (Questions 71-140)
  // Mixed Topics from here on
  {
    id: 'mgt_q71',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Ensuring the safety, health and welfare of the employees is the primary purpose of the ---',
    options: ['Factories Act, 1948', 'Industrial Dispute Act', 'Workman Compensation Act', 'Minimum Wages Act'],
    correctAnswer: 'Factories Act, 1948',
  },
  {
    id: 'mgt_q72',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'A person who has ultimate control over the affairs of the factory under Factories Act, 1948 is called as ---',
    options: ['Manager', 'Chairman', 'Occupier', 'None of the above'],
    correctAnswer: 'Occupier',
  },
  {
    id: 'mgt_q73',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Leave with wages is allowed for employees if they work for ______ days in a month',
    options: ['28', '20', '30', '31'],
    correctAnswer: '20',
  },
  {
    id: 'mgt_q74',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'An adult worker can work up to ___ hrs in a day as per factories Act, 1948.',
    options: ['9', '8', '12', '16'],
    correctAnswer: '8',
  },
  {
    id: 'mgt_q75',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Section 22 and 23 of the industrial dispute Act says about ---',
    options: ['Fencing of machineries', 'Facing of machineries', 'Work on near machinery in motion', 'strikes and lock-out'],
    correctAnswer: 'strikes and lock-out',
  },
  {
    id: 'mgt_q76',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The Section 20 of the Factories act discusses about--- -',
    options: ['Latrines and Urinals', 'Drinking water', 'Spittoons', 'Lighting'],
    correctAnswer: 'Spittoons',
  },
  {
    id: 'mgt_q77',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Under Minimum Wages Act an Adult means a Person who has completed a age of --- years',
    options: ['18', '15', '16', '19'],
    correctAnswer: '18',
  },
  {
    id: 'mgt_q78',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'The employment of young person on dangerous machines shall be prohibited by ...... the Act.',
    options: ['Industrial dispute', 'Workmen Compensation', 'Factory', 'None of the above'],
    correctAnswer: 'Factory',
  },
  {
    id: 'mgt_q79',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'To close down a factory. the occupier has to give ______ days notice to the authorities',
    options: ['30', '60', '90', '15'],
    correctAnswer: '60',
  },
  {
    id: 'mgt_q80',
    subjectId: 'management',
    topic: 'Industrial Acts and Labour Laws',
    text: 'Under the Factories Act, white washing of the factory building should be carried out in every ______ months',
    options: ['12', '24', '26', '14'],
    correctAnswer: '14',
  },
  {
    id: 'mgt_q81',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: '"Management is the getting the thing done by others" this is said by',
    options: ['Henry Gantt', 'Druckar', 'Mary Parker', 'Henry Fayol'],
    correctAnswer: 'Mary Parker',
  },
  {
    id: 'mgt_q82',
    subjectId: 'management',
    topic: 'Safety Management',
    text: 'Accident may occur due to',
    options: ['fire drill', 'unsafe act of worker', 'good concentration on the work', 'All of the above'],
    correctAnswer: 'unsafe act of worker',
  },
  {
    id: 'mgt_q83',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Controlling function includes the following processes. 1. Analyzing the actual performance 2 Finding out the reasons for discrepancies 3 Evaluating the performance 4 Establishing the standards of work performance. The correct sequence in which these processes are usually carried out is-',
    options: ['1, 2, 3, 4', '1, 4, 2, 3', '4,1,3,2', '1,4,3,2'],
    correctAnswer: '4,1,3,2',
  },
  {
    id: 'mgt_q84',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Which one of the following statement is correct- 1 Planning and controlling are one and the same. 2 Controlling is a part of the planning process. 3 Controlling is a substitute for planning 4 A control process is meaningless without preset standards',
    options: ['2', '3', '1', '4'],
    correctAnswer: '4',
  },
  {
    id: 'mgt_q85',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Which basic function of management includes setting standards such as production of engine piston with desired quality standards',
    options: ['Planning', 'Controlling', 'Directing', 'All above'],
    correctAnswer: 'Controlling',
  },
  {
    id: 'mgt_q86',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Which specific activities listed below are part of the controlling function-',
    options: ['giving each subordinates a specific task', 'recruiting skilled employees', 'developing rules and regulations', 'checking to see how actual performance compares with standards.'],
    correctAnswer: 'checking to see how actual performance compares with standards.',
  },
  {
    id: 'mgt_q87',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Directing function of management implies- 1.Planning 2. Staffing 3. Leadership. 4. Motivation',
    options: ['1&2', '3&4', '2&4', '2,3&4'],
    correctAnswer: '3&4',
  },
  {
    id: 'mgt_q88',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Consider the following basic steps involved in the process of controlling- 1. Identifying the strategic control points. 2. Establishment of standards 3. Measuring performance against standards 4. Correcting deviations from the standards Arrange it in order in which it is carried out.',
    options: ['1, 4, 2, 3', '1, 2, 3, 4', '2, 1, 3, 4', '2, 3, 1, 4'],
    correctAnswer: '2, 1, 3, 4',
  },
  {
    id: 'mgt_q89',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Establishment of standards , comparing actual results with standards and taking corrective action are the steps in-',
    options: ['Planning', 'Controlling', 'Directing', 'Organizing'],
    correctAnswer: 'Controlling',
  },
  {
    id: 'mgt_q90',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Which of the following management functions are closely related-',
    options: ['Organization and staffing', 'Planning and Controlling', 'Directing and Controlling', 'Planning and Staffing.'],
    correctAnswer: 'Directing and Controlling',
  },
  {
    id: 'mgt_q91',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'which of the following would be included in the controlling function',
    options: ['Setting corporate goals.', 'Explaining routines', 'Setting performance standards', 'Giving assignment'],
    correctAnswer: 'Setting performance standards',
  },
  {
    id: 'mgt_q92',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: '--- is the right to make the decision, to direct the work to workers and to give order to subordinates.',
    options: ['Leadership', 'Authority', 'Directing', 'Responsibility'],
    correctAnswer: 'Directing',
  },
  {
    id: 'mgt_q93',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: '--- are authorized to direct the work and issue of orders workers at lower level of management.',
    options: ['Top level Manager', 'Middle level manager', 'Supervisor', 'HR Manager'],
    correctAnswer: 'Supervisor',
  },
  {
    id: 'mgt_q94',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Directing is a continuous task of',
    options: ['Making decisions, giving orders and providing leadership', 'Controlling the process and cost of product', 'bringing simplicity in accomplishing set goal', 'Improving the efficiency of group only'],
    correctAnswer: 'Making decisions, giving orders and providing leadership',
  },
  {
    id: 'mgt_q95',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'In order to achieve the desired results , the effort should be in proper direction, this is ensured by the following function of management 1. Directing 2. Coordinating 3. Forecasting 4. Controlling',
    options: ['1&4', '2&3', '2&4', '1&3'],
    correctAnswer: '1&4',
  },
  {
    id: 'mgt_q96',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Order issued by Supervisor must have clarity and completeness to-',
    options: ['achieve set goal of firm', 'fulfill the requirements of vision and mission of firm', 'avoid material waste and profit', 'get desired results as per set standard and increase in productivity'],
    correctAnswer: 'get desired results as per set standard and increase in productivity',
  },
  {
    id: 'mgt_q97',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Issuing instructions to subordinates are necessary to- 1.achieve desired set of standards 2.increase productivity 3.make efficient use of machine and equipment. 4.to maintain discipline in only one section.',
    options: ['1,2,4', '2,3,4', '1,3,4', '1,2,3'],
    correctAnswer: '1,2,3',
  },
  {
    id: 'mgt_q98',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Supervisors should issue the order with no ambiguity and with completeness to-',
    options: ['understand the order by average worker', 'to get the idea of volume of work to be done.', 'help in setting the standards', 'get clarity in performance and achieve target'],
    correctAnswer: 'get clarity in performance and achieve target',
  },
  {
    id: 'mgt_q99',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Supervisor can bring clarity in order and in performance by-',
    options: ['showing and illustrating different stages of work gradually one at a time.', 'demonstrating use of tools and machines', 'showing finished job to worker', 'all above.'],
    correctAnswer: 'all above.',
  },
  {
    id: 'mgt_q100',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Establish standards and evaluation of performance is the parameters of-',
    options: ['Planning', 'Controlling', 'Directing', 'Management'],
    correctAnswer: 'Controlling',
  },

  // Management (22509) Questions
  // Batch 3 (Questions 101-157)
  {
    id: 'mgt_q101',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Directing is not concerned with the following function-',
    options: ['communication', 'supervising', 'leadership', 'forecasting and management'],
    correctAnswer: 'forecasting and management',
  },
  {
    id: 'mgt_q102',
    subjectId: 'management',
    topic: 'Planning and Organizing', // Could be Directing and Controlling (Coordinating)
    text: 'Ensuring that everything is carried out according to plan is the part of the process-',
    options: ['Planning', 'Staffing', 'Organizing', 'Coordinating'],
    correctAnswer: 'Coordinating',
  },
  {
    id: 'mgt_q103',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Some times subordinates were found confused about their work, this mainly happens due to',
    options: ['change in working place and machine', 'lack of clarity and completeness in order issued by supervisor', 'lack of confidence and knowledge', 'physically not fit.'],
    correctAnswer: 'lack of clarity and completeness in order issued by supervisor',
  },
  {
    id: 'mgt_q104',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Prateek is working in multinational company in Mumbai. When he was new he does not know the rules , regulations and Quality policy of company. He was poor in some technical and generic skill. He was lacking in confidence and communication. But his supervisor Mr. Atul constantly encourages him and motivates to work. He demonstrates the work and direct him to do individually. Now Prateek is a skilled employee and working in the direction and leadership of Mr. Atul. Identify the function of management',
    options: ['Coordination', 'Directing.', 'Leadership', 'Communication'],
    correctAnswer: 'Directing.',
  },
  {
    id: 'mgt_q105',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Main objectives of budget is to _____',
    options: ['Develope existing and future projects', 'Test and implement program', 'planning and controlling of activities', 'All of these'],
    correctAnswer: 'planning and controlling of activities',
  },
  {
    id: 'mgt_q106',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Supervisor should plan for overall and effective utilization of ______.',
    options: ['Man', 'Machine', 'Material', 'All of the above'],
    correctAnswer: 'All of the above',
  },
  {
    id: 'mgt_q107',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Good planning of supervisor leads to ______.',
    options: ['Minimum waste of material.', 'Higher productivity.', 'Better supervision.', 'All of the above'],
    correctAnswer: 'All of the above',
  },
  {
    id: 'mgt_q108',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Good planning of supervisor helps in ______.',
    options: ['Make or buy decision.', 'Determination of selling price', 'Budgeting for materials and manpower', 'None of above'],
    correctAnswer: 'Budgeting for materials and manpower',
  },
  {
    id: 'mgt_q109',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Matching human needs with jobs needs is also called as ______.',
    options: ['Manpower planning.', 'Material planning.', 'Machine planning.', 'None of above'],
    correctAnswer: 'Manpower planning.',
  },
  {
    id: 'mgt_q110',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts', // Roles of Supervisor
    text: 'Supervisor has to play roles of ______.',
    options: ['Engineer', 'Resource Manager', 'Team leader', 'All of the above'],
    correctAnswer: 'All of the above',
  },
  {
    id: 'mgt_q111',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: '______ is responsible for effective utilization of Machines on the shop-floor.',
    options: ['Machine operator', 'Quality inspector', 'Supervisor', 'None of above'],
    correctAnswer: 'Supervisor',
  },
  {
    id: 'mgt_q112',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: '______ is responsible for effective utilization of manpower on the shop-floor.',
    options: ['Machine operator', 'Quality inspector', 'Supervisor', 'None of above'],
    correctAnswer: 'Supervisor',
  },
  {
    id: 'mgt_q113',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Good planning of supervisor can ______.',
    options: ['Reduce manufacturing cycle time', 'Maintain or improve product quality', 'Reduce delays, and damage', 'All of the above'],
    correctAnswer: 'All of the above',
  },
  {
    id: 'mgt_q114',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Supervisor planning ______.',
    options: ['minimises future uncertainties in production.', 'Maximize future uncertainties in production.', 'has no effect on future uncertainties in production.', 'None of above'],
    correctAnswer: 'minimises future uncertainties in production.',
  },
  {
    id: 'mgt_q115',
    subjectId: 'management',
    topic: 'Planning and Organizing', // Also touches on Safety Management
    text: 'Along with manpower planning supervisor should ______.',
    options: ['Promote safety and good working conditions.', 'Maintain or improve product quality', 'Reduce delays, and damage', 'All of the above'],
    correctAnswer: 'All of the above',
  },
  {
    id: 'mgt_q116',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Supervisor involved in ______ planning.',
    options: ['Long term', 'strategic', 'operational', 'Corporate'],
    correctAnswer: 'operational',
  },
  {
    id: 'mgt_q117',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Which of the following is not correct statement regarding operational planning?',
    options: ['It decides the detailed use of resources for achieving targets.', 'It is carried at lower level of management.', 'It is more detailed.', 'It is long term planning.'],
    correctAnswer: 'It is long term planning.',
  },
  {
    id: 'mgt_q118',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'The first step in planning process is ______.',
    options: ['Establishing goals/objectives', 'Establishing planning premises', 'Deciding the planning period', 'Identification of alternatives'],
    correctAnswer: 'Establishing goals/objectives',
  },
  {
    id: 'mgt_q119',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Deciding the planning period involves ______.',
    options: ['decision regarding time span', 'decision regarding alternatives', 'decision regarding processes', 'decision regarding control'],
    correctAnswer: 'decision regarding time span',
  },
  {
    id: 'mgt_q120',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Arrange the following planning steps in chronological order? 1. Identification of alternatives 2. Evaluation and selection of alternative 3. Measuring and controlling the process: 4. Developing derivative/supportive plans',
    options: ['1-2-3-4', '1-2-4-3', '2-1-3-4', '1-3-2-4'],
    correctAnswer: '1-2-4-3',
  },
  {
    id: 'mgt_q121',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'The planning to buy raw materials is a plan to ______.',
    options: ['support main plain.', 'support alternative plan', 'support measuring activity.', 'None of above'],
    correctAnswer: 'support main plain.',
  },
  {
    id: 'mgt_q122',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: '"Management is the art of getting the work done through and with the people in formally organized groups."These words were told by:',
    options: ['Harold Koontz', 'F.W.Taylor', 'Henry Fayol', 'Mary Parker Follet'],
    correctAnswer: 'Harold Koontz',
  },
  {
    id: 'mgt_q123',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'The various steps of planning are given below: (a) premising (b) establish objectives (c) evaluate alternative course (d) decide planning period (e)measuring and controlling process (f) Develop derivative plans The proper sequence of planning from the first to last step is:',
    options: ['a-c-b-d-e-f', 'b-a-d-c-f-e', 'a-b-c-d-e-f', 'b-a-c-d-e-f'],
    correctAnswer: 'b-a-d-c-f-e',
  },
  {
    id: 'mgt_q124',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'The process of deciding what to do, when to do and how to do is called :',
    options: ['Organizing', 'Controlling', 'Planning', 'Directing'],
    correctAnswer: 'Planning',
  },
  {
    id: 'mgt_q125',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Decision making is very fast in :',
    options: ['line organisation', 'functional organisation', 'line and staff organisation', 'project organization'],
    correctAnswer: 'line organisation',
  },
  {
    id: 'mgt_q126',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'The objectives and policies of an organization is set by:',
    options: ['Middle management', 'Top management', 'Lower management', 'All of the above'],
    correctAnswer: 'Top management',
  },
  {
    id: 'mgt_q127',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Which of the following is the first step of organizing process?',
    options: ['formulating plans and policies', 'Establish enterprise objectives', 'Identify and classify activities', 'delegation of activities'],
    correctAnswer: 'Establish enterprise objectives',
  },
  {
    id: 'mgt_q128',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Arrange the following steps involved in the process of control in proper sequence: 1. Establishment of standards of work performance. 2. Measuring actual performance 3. Comparing actual performance with established standards. 4. corrective action to eliminate deviations from standards',
    options: ['1-2-3-4', '2-1-3-4', '2-3-1-4', '3-1-2-4'],
    correctAnswer: '1-2-3-4',
  },
  {
    id: 'mgt_q129',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Which of the following is true with respect to planning function?',
    options: ['Monitor whether work is done properly', 'Allocation of work to all', 'Make a blue print of ideas and work.', 'Compare the work done with established standards'],
    correctAnswer: 'Make a blue print of ideas and work.',
  },
  {
    id: 'mgt_q130',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Which of the following orders indicate the correct logical order of managerial functions?',
    options: ['Organizing, planning,directing,staffing, controlling', 'Planning,organizing,staffing, directing,controlling', 'Planning,directing,organizing,staffing, controlling', 'Organizing, planning , staffing, controlling,,directing'],
    correctAnswer: 'Planning,organizing,staffing, directing,controlling',
  },
  {
    id: 'mgt_q131',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'One of the management principles implies that each subordinate should have only one superior whose orders he has to obey.This principle refers to:',
    options: ['Authority and responsibility', 'Unity of direction', 'Scalar chain', 'Unity of command'],
    correctAnswer: 'Unity of command',
  },
  {
    id: 'mgt_q132',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'The main advantage of functional organization is:',
    options: ['simplicity', 'expert advice', 'specialization', 'experience'],
    correctAnswer: 'specialization',
  },
  {
    id: 'mgt_q133',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'In line and staff organization,the authority lies with:',
    options: ['line executive', 'staff executive', 'both line and staff', 'none of the above'],
    correctAnswer: 'line executive',
  },
  {
    id: 'mgt_q134',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'The main advantage of line and staff organization is:',
    options: ['expert advice from specialists', 'experience', 'simple structure', 'quick decisions'],
    correctAnswer: 'expert advice from specialists',
  },
  {
    id: 'mgt_q135',
    subjectId: 'management',
    topic: 'Planning and Organizing', // Staffing is part of Organizing broadly
    text: 'Which of the following are the functions of staffing? 1.Recruiting 2.Training 3.Directing 4.Appraisal',
    options: ['1,2,3 and 4', '1,2 and 4', '1,2 and 3', '1 and 2'],
    correctAnswer: '1,2 and 4',
  },
  {
    id: 'mgt_q136',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'The ability to think in abstract terms to analyze and diagnose problems and make use of lateral thinking is called',
    options: ['analytical skills', 'technical skills', 'conceptual skills', 'decision making skills'],
    correctAnswer: 'conceptual skills',
  },
  {
    id: 'mgt_q137',
    subjectId: 'management',
    topic: 'Compensation and Wage Policies',
    text: 'The rate of minimum wage is fixed with respect to ......',
    options: ['Consumer Price Index', 'Cost of Living allowance', 'None of A & B', 'Both of A & B'],
    correctAnswer: 'Cost of Living allowance',
  },
  {
    id: 'mgt_q138',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'In line and staff organization,the staff performs the function of ---',
    options: ['Management', 'Advising the management', 'Assigning responsibility', 'Administration'],
    correctAnswer: 'Advising the management',
  },
  {
    id: 'mgt_q139',
    subjectId: 'management',
    topic: 'Planning and Organizing', // Delegation is part of Organizing
    text: 'The general manager of a firm asks the sales manager to recruit a salesman on his behalf.This is an example of:',
    options: ['decentralization of authority', 'delegation of responsibility', 'delegation of authority', 'division of authority'],
    correctAnswer: 'delegation of authority',
  },
  {
    id: 'mgt_q140',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Directing function of management refers to which of the following functions? 1.Planning 2. Motivation 3.leadership 4.Controlling',
    options: ['1 and 2', '2 and 3', '2, 3 and 4', '1,2, 3 and 4'],
    correctAnswer: '2 and 3',
  },
  {
    id: 'mgt_q141',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Which of the following skills is equally important at all levels of management?',
    options: ['Technical skills', 'Conceptual skills', 'Human skills', 'Design skills'],
    correctAnswer: 'Human skills',
  },
  {
    id: 'mgt_q142',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'The managerial skills which involve the ability to see the organization as a whole is called:--- .',
    options: ['Conceptual skills', 'Technical skills', 'Human skills', 'Tactical skills'],
    correctAnswer: 'Conceptual skills',
  },
  {
    id: 'mgt_q143',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Identify the managerial skills necessary for top level management.:',
    options: ['Technical skills and human skills', 'Human skills and conceptual skills', 'Technical skills and conceptual skills .', 'All of the above'],
    correctAnswer: 'Human skills and conceptual skills',
  },
  {
    id: 'mgt_q144',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'The ability of a manager to work effectively with others and build cooperative work groups to achieve organizational goals is called ---',
    options: ['Technical skills', 'Design skills', 'Human skills', 'Conceptual skills'],
    correctAnswer: 'Human skills',
  },
  {
    id: 'mgt_q145',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Ambiguous and incomplete order issued by supervisor results in 1 Poor communication 2 Incapability of supervisor to get work done. 3 Loss of time, money and energy 4 Higher idle time of employees',
    options: ['1&4', '2&3', '3&4', '2&4'],
    correctAnswer: '3&4',
  },
  {
    id: 'mgt_q146',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Employees who are more concerned about their work may loss their interest and enthusiasm towards work because of 1 Ambiguous order issued by supervisor 2 Feasibility of order is not possible 3 There is no clarity and completeness in order 4 Lack of motivation from supervisor',
    options: ['1&2', '2,3&4', '1,2,3 & 4', '1,3&4'],
    correctAnswer: '1,2,3 & 4',
  },
  {
    id: 'mgt_q147',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: '--- may lead the make employees confused about their work.',
    options: ['Not feasible and ambiguous order', 'Supervisor correct decision', 'Quality Policy', 'None of the above'],
    correctAnswer: 'Not feasible and ambiguous order',
  },
  {
    id: 'mgt_q148',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'To complete the work without any problem and in time employees mainly needs-',
    options: ['Conducive environment', 'Knowledge and skill', 'Order with clarity, completeness and having feasibility', 'Good salary package'],
    correctAnswer: 'Order with clarity, completeness and having feasibility',
  },
  {
    id: 'mgt_q149',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Proper instructions issued by supervisor to his subordinates result in-',
    options: ['Maintain quality standards', 'Completeness of work in time', 'Reduce heavy rejection', 'All above'],
    correctAnswer: 'All above',
  },
  {
    id: 'mgt_q150',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'While issuing order supervisor shall take care of- 1 present situation of his section 2 order must be issued loudly and in hard words to get work done. 3. provide only necessary information 4. checking the desired impact of order or repeat it.',
    options: ['1&2', '2&3', '3&4', '4&1'],
    correctAnswer: '3&4',
  },
  {
    id: 'mgt_q151',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Supervisor can reduce the anxiety of employee which affects on his performance by-',
    options: ['Showing sympathy and empathy towards him.', 'Helping in his work', 'Personal counseling', 'Allowing him to take leave to get refresh'],
    correctAnswer: 'Personal counseling',
  },
  {
    id: 'mgt_q152',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Personal counseling is the technique by which supervisor can-',
    options: ['influence the employees', 'teach and trained the employees', 'advise the troubled employee to reduce his anxieties', 'Come closer to employee'],
    correctAnswer: 'advise the troubled employee to reduce his anxieties',
  },
  {
    id: 'mgt_q153',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Following are the features of the perfect order issued by supervisor- 1 Clarity and completeness 2 Feasibility and timely bounded 3 Consideration of worker choice and interest 4 Incomplete orders from higher authority',
    options: ['1&3', '1&2', '2&4', '3&4'],
    correctAnswer: '1&2',
  },
  {
    id: 'mgt_q154',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Mr. Vijay is working in renowned company as worker. He is a sincere & obedient employee. But from last few days his behavior is changed. Most of the time he gets annoyed and behave erratically. He lacks his interest in work thus his performance also get reduced and more rejection takes place. Mr. Atul is a supervisor in his section, noticed the change in behavior of Mr. Vijay. He take him in confidence and advise. So that Mr. Vijay feels relax and again he concentrates on his work',
    options: ['Personal problem solving', 'Personal counseling', 'Personal controlling', 'Personal Directing'],
    correctAnswer: 'Personal counseling',
  },
  {
    id: 'mgt_q155',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Identify the step of controlling process applicable in following case- In a company a manager is trying to find out the deviation between the actual number of parts produced and the desired number. He already knows about the standards as the company has assigned him a definite quantity of parts to be produced',
    options: ['taking corrective action', 'analyzing deviation', 'comparing actual and standard performance', 'setting standard'],
    correctAnswer: 'comparing actual and standard performance',
  },
  {
    id: 'mgt_q156',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Mr Rajesh wants to set standard to be achieved in both qualitative and quantitative in his section. He wants to judge the motivation, skill level and satisfaction of the subordinates. All these things will require qualitative standards while on other hand he has to set quantitative standards for the number of units produced. Identify the step of controlling process applicable in this case.',
    options: ['Setting standard', 'analyzing standard', 'controlling standard', 'all above'],
    correctAnswer: 'Setting standard',
  },
  {
    id: 'mgt_q157',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Sachin is working in tool manufacturing company and have been assigned the job of judging the output of production in a neutral and reliable way. He is applying different techniques for achieving this aim. He is also keeping the units of measurement same to that of the units of set standard. Identify the step of controlling process applicable in this case.',
    options: ['Setting standard', 'Measurement of actual performance', 'Analyzing facts.', 'Taking corrective action'],
    correctAnswer: 'Measurement of actual performance',
  },
  // Management (22509) Questions
  // Batch 3 (Questions 158-210)
  {
    id: 'mgt_q158',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'The number of subordinates that report to an executive or the number of subordinates that an executive can supervise directly is called:',
    options: ['Authority', 'Span of control', 'Coordination', 'Effective delegation'],
    correctAnswer: 'Span of control',
  },
  {
    id: 'mgt_q159',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Which of the following is not a principle of management?',
    options: ['Remuneration', 'Order', 'Budget', 'Scalar chain'],
    correctAnswer: 'Budget',
  },
  {
    id: 'mgt_q160',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: '"Espirit De Corps"refers to',
    options: ['Level of management', 'Principles of motion economy', 'Principles of organization', 'Principles of management'],
    correctAnswer: 'Principles of management',
  },
  {
    id: 'mgt_q161',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Who is known as father of scientific management?',
    options: ['Henry Fayol', 'Gilbreth', 'F.W.Taylor', 'Elton Mayo'],
    correctAnswer: 'F.W.Taylor',
  },
  {
    id: 'mgt_q162',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Match the Pairs: 1.F.W.Taylor (i) Hierarchy of needs 2. Frank Gilbreth (ii) Father of Scientific management 3.Henri Fayol (iii) Time and Motion study 4. Abraham Maslow (iv) General principles of management',
    options: ['1-ii 2-iii 3-iv 4-i', '1-ii 2-iv 3-iii 4-i', '1-iv 2-ii 3-iii 4-i', '1-iv 2-iii 3-i 4-ii'],
    correctAnswer: '1-ii 2-iii 3-iv 4-i',
    explanation: "Corrected options for Henri Fayol to 'General principles of management' based on common understanding.",
  },
  {
    id: 'mgt_q163',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Management carries out the policies of ---through the framework of the --- .',
    options: ['Organization, Administration', 'Management, Administration', 'Administration, Organization', 'Organization, Management'],
    correctAnswer: 'Administration, Organization',
  },
  {
    id: 'mgt_q164',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Administration is concerned with:',
    options: ['Implementing the policies of the organization', 'Deciding the goals and policies of the organization', 'Development of different parts of the organization in proper order.', 'None of the above'],
    correctAnswer: 'Deciding the goals and policies of the organization',
  },
  {
    id: 'mgt_q165',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: '______ is a mechanism or structure that enables living things to work effectively together',
    options: ['Management', 'Planning', 'Organization', 'Administration'],
    correctAnswer: 'Organization',
  },
  {
    id: 'mgt_q166',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Administration is an activity at:',
    options: ['Middle level management', 'Top level management', 'Lower level management', 'none of the above'],
    correctAnswer: 'Top level management',
  },
  {
    id: 'mgt_q167',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: '______ is the process of getting activities completed efficiently and effectively with and through the people',
    options: ['Supervision', 'Leading', 'Controlling', 'Management'],
    correctAnswer: 'Management',
  },
  {
    id: 'mgt_q168',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Decision making, policy making and making necessary adjustments is concerned mainly with_____',
    options: ['Staffing', 'Administration', 'Organization', 'None of the given options'],
    correctAnswer: 'Administration',
  },
  {
    id: 'mgt_q169',
    subjectId: 'management',
    topic: 'Directing and Controlling', // Communication
    text: 'find odd thing out with respect to type of communication (upward/downward)',
    options: ['open door policy', 'provide feedback to subordinates', 'participative techniues', 'gravience redressal procedure'],
    correctAnswer: 'provide feedback to subordinates',
  },
  {
    id: 'mgt_q170',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Management is a/an:',
    options: ['determinative function', 'executive function', 'decision making function', 'top level function'],
    correctAnswer: 'executive function',
  },
  {
    id: 'mgt_q171',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Function of Management involves selecting missions and objectives and the actions to achieve them',
    options: ['Planning', 'Organizing', 'Leading', 'None of the given options'],
    correctAnswer: 'Planning',
  },
  {
    id: 'mgt_q172',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Top level management includes:',
    options: ['Superintendents and supervisors', 'Production manager and finance manager', 'Board of directors and chief executives', 'Inspectors and marketing managers'],
    correctAnswer: 'Board of directors and chief executives',
  },
  {
    id: 'mgt_q173',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Scalar organization is the other name given to:',
    options: ['line and staff organization', 'line organisation', 'functional organization', 'project organization'],
    correctAnswer: 'line organisation',
  },
  {
    id: 'mgt_q174',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'The line of authority from the chief executives to the lowest level of organization is called:',
    options: ['unity of command', 'Unity of direction', 'order', 'Scalar chain'],
    correctAnswer: 'Scalar chain',
  },
  {
    id: 'mgt_q175',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Which function of management process consists of measuring results, comparing these results with standard expectations and applying corrective actions if needed?',
    options: ['Organizing', 'Controlling', 'Planning', 'Directing'],
    correctAnswer: 'Controlling',
  },
  {
    id: 'mgt_q176',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Which of the following is not a correct advantage of line organization?',
    options: ['simple', 'flexible', 'speedy action', 'specialist advice'],
    correctAnswer: 'specialist advice',
  },
  {
    id: 'mgt_q177',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Measuring and correcting individual and organizational performance to ensure that events confirm to plans is done by ______ function',
    options: ['Staffing', 'Planning', 'Controlling', 'Organizing'],
    correctAnswer: 'Controlling',
  },
  {
    id: 'mgt_q178',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Meaning of “Esprit de corps” according to Henry Fayol Principles is that---',
    options: ['chain of superiors', 'in union there is strength', 'centralization of authority', 'respect for agreements'],
    correctAnswer: 'in union there is strength',
  },
  {
    id: 'mgt_q179',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'The “Father of Modern Management theory” formulated principles of management',
    options: ['6', '10', '14', '12'],
    correctAnswer: '14',
  },
  {
    id: 'mgt_q180',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'The loyalty and devotion should be elicited from personnel by a combination of kindliness and justice between managers and with subordinates',
    options: ['Equity', 'Stability', 'Order', 'Initiative'],
    correctAnswer: 'Equity',
  },
  {
    id: 'mgt_q181',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Line organization is also known as ______',
    options: ['Functional Organization', 'Military Organization', 'Project Organization', 'Multiple Organization'],
    correctAnswer: 'Military Organization',
  },
  {
    id: 'mgt_q182',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'is also known as Functional Organization',
    options: ['Project Organization', 'Department Organization', 'Staff Organization', 'None of the given options'],
    correctAnswer: 'Staff Organization',
  },
  {
    id: 'mgt_q183',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'The proficiency in handling methods, processes and techniques of a particular kind of business refer to ______ managerial skills',
    options: ['Conceptual skills', 'Technical skills', 'Decision making skills', 'None of the given options'],
    correctAnswer: 'Technical skills',
  },
  {
    id: 'mgt_q184',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Technical skills are essential for ______ level management',
    options: ['Top level', 'Middle level', 'Lower level', 'None of the given options'],
    correctAnswer: 'Lower level',
  },
  {
    id: 'mgt_q185',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'To recognize inter-relationships among different functions of the business and external forces and to guide effectively for organization effort ______ skills is requested',
    options: ['Conceptual', 'Technical', 'Organisational', 'Human relation'],
    correctAnswer: 'Conceptual',
  },
  {
    id: 'mgt_q186',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: '______ skills help select and fix different people at different work',
    options: ['Human relation', 'Decision making', 'Organisational', 'Technical'],
    correctAnswer: 'Organisational',
  },
  {
    id: 'mgt_q187',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'skills refers to ability to work effectively with others and build cooperative work groups to achieve organizational goals',
    options: ['Organisational', 'Human relation', 'Leadership', 'Motivating'],
    correctAnswer: 'Human relation',
  },
  {
    id: 'mgt_q188',
    subjectId: 'management',
    topic: 'Directing and Controlling', // Leadership
    text: 'The ability to inspire confidence and trust in the subordinates in order to have maximum cooperation from them getting the work done is ______ skills',
    options: ['Motivating', 'Leadership', 'Decision making', 'Technical'],
    correctAnswer: 'Leadership',
  },
  {
    id: 'mgt_q189',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'The employees should receive orders and instructions from one supervision only will come under ______ principles of Management',
    options: ['Unity of Direction', 'Unity of Command', 'Equity of Treatment', 'Discipline'],
    correctAnswer: 'Unity of Command',
  },
  {
    id: 'mgt_q190',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Fredrick Taylor stressed on',
    options: ['Selecting the right people for the right job', 'Division of labour', 'Unity of command', 'Unity of direction'],
    correctAnswer: 'Selecting the right people for the right job',
  },
  {
    id: 'mgt_q191',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Who developed the concept of \'hierarchy of needs\' in regards to motivation',
    options: ['F.W. Taylor', 'Abraham Maslow', 'Max Weber', 'Mary Follet'],
    correctAnswer: 'Abraham Maslow',
  },
  {
    id: 'mgt_q192',
    subjectId: 'management',
    topic: 'Compensation and Wage Policies', // Also Intro to Management Concepts
    text: 'To motivate workers Taylor suggested ______',
    options: ['To give less work', 'To provide festival bonus', 'Differential piece rate plan', 'To pay more salary'],
    correctAnswer: 'Differential piece rate plan',
  },
  {
    id: 'mgt_q193',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'The board objectives and policies are decided by',
    options: ['Regional manager', 'Marketing manager', 'Supervisor', 'Chief Executive Officer'],
    correctAnswer: 'Chief Executive Officer',
  },
  {
    id: 'mgt_q194',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'When we classify managers according to their levels in the organization, they are described as ______',
    options: ['Functional, staff and line managers', 'Top managers, middle managers and supervisors', 'High level and lower level manager', 'Work managers and general manager'],
    correctAnswer: 'Top managers, middle managers and supervisors',
  },
  {
    id: 'mgt_q195',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Which of the following is not a function of the management process',
    options: ['Directing', 'Controlling', 'Processing', 'Leading'],
    correctAnswer: 'Processing',
  },
  {
    id: 'mgt_q196',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Getting work done with a minimum effort, expense or waste is the definition of ______',
    options: ['Efficiency', 'Effectiveness', 'Organizing', 'Planning'],
    correctAnswer: 'Efficiency',
  },
  {
    id: 'mgt_q197',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'The type of planning which sets direction in which the organization wants to proceed in future is called:',
    options: ['Contingency planning', 'strategic planning', 'tactical planning', 'operational planning'],
    correctAnswer: 'strategic planning',
  },
  {
    id: 'mgt_q198',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: '______ are the organization objectives and ______ are the documented ways that organization intends to meet those objectives',
    options: ['Standing plans ; Single use plans', 'Stated goals ; Real goals', 'Specific goals ; Directional plans', 'Goals ; Plans'],
    correctAnswer: 'Goals ; Plans',
  },
  {
    id: 'mgt_q199',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: '______ is the judgment of the future',
    options: ['Mission', 'Forecasting', 'Planning', 'Organizing'],
    correctAnswer: 'Forecasting',
  },
  {
    id: 'mgt_q200',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Who is not a middle level manager',
    options: ['General Manager', 'Production Manager', 'Stores Manager', 'Marketing Manager'],
    correctAnswer: 'General Manager',
  },
  {
    id: 'mgt_q201',
    subjectId: 'management',
    topic: 'Directing and Controlling', // Communication
    text: 'Advantages of written communication are',
    options: ['It gives evidences about event', 'It provide permanent record for future', 'Reduces chances of misinterpretation', 'All of the above'],
    correctAnswer: 'All of the above',
  },
  {
    id: 'mgt_q202',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Directing involves functions such as ______ and ______',
    options: ['Staffing and Planning', 'Leadership and Motivation', 'Controlling and Coordinating', 'Planning and Decision making'],
    correctAnswer: 'Leadership and Motivation',
  },
  {
    id: 'mgt_q203',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'The first step in the strategic planning process is to :',
    options: ['set the company goals and objectives', 'define the company vision', 'to decide other functional strategies.', 'to lay down the rules and policies.'],
    correctAnswer: 'define the company vision',
  },
  {
    id: 'mgt_q204',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: '______ is a policy making function',
    options: ['Production', 'Work', 'Plan', 'Administration'],
    correctAnswer: 'Administration',
  },
  {
    id: 'mgt_q205',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: '______ does not belongs to Henry Fayol’s principles of management',
    options: ['Scalar chain', 'Authority', 'Standardization', 'Discipline'],
    correctAnswer: 'Standardization',
  },
  {
    id: 'mgt_q206',
    subjectId: 'management',
    topic: 'Directing and Controlling', // Motivation
    text: 'The process of inspiring the subordinates to put in their best known as ______',
    options: ['Team work', 'Motivation', 'Management', 'Leadership'],
    correctAnswer: 'Motivation',
  },
  {
    id: 'mgt_q207',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'The process of monitoring, comparing and correcting is called ______',
    options: ['Leading', 'Decision making', 'Controlling', 'Coordinating'],
    correctAnswer: 'Controlling',
  },
  {
    id: 'mgt_q208',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'The three essential managerial skills required by any successful manager in an organization are ______',
    options: ['Technical, human and social', 'Human, empirical and conceptual', 'Technical, interpersonal and controlling', 'Technical, human and conceptual'],
    correctAnswer: 'Technical, human and conceptual',
  },
  {
    id: 'mgt_q209',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'In a line organization the authority flows from',
    options: ['Subordinate to Subordinate', 'Superior to Superior', 'Superior to Subordinate', 'Subordinate to Superior'],
    correctAnswer: 'Superior to Subordinate',
  },
  {
    id: 'mgt_q210',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Which is not the correct type of plan?',
    options: ['Action plan', 'Corporate plan', 'Operational plan', 'Management plan'],
    correctAnswer: 'Management plan',
  },
  // Management (22509) Questions
  // Batch 4 (Questions 211-256)
  {
    id: 'mgt_q211',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'After plans have been made and the organization has been established and staffed, the next step is ______',
    options: ['Controlling', 'Directing', 'Decision making', 'Planning'],
    correctAnswer: 'Directing',
  },
  {
    id: 'mgt_q212',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Planning may fail because of ______',
    options: ['Absence of winning attitude', 'Guiding the subordinates', 'Monitoring of programme', 'Takes corrective action'],
    correctAnswer: 'Absence of winning attitude',
  },
  {
    id: 'mgt_q213',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: '______ minimizes work pressures and dead line tensions',
    options: ['Organizing', 'Controlling', 'Planning', 'Leadership'],
    correctAnswer: 'Planning',
  },
  {
    id: 'mgt_q214',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: '______ and ______ plans are the types of planning in management process',
    options: ['Stability and initiative', 'Operational and strategic', 'Directing and motivation', 'None of the given options'],
    correctAnswer: 'Operational and strategic',
  },
  {
    id: 'mgt_q215',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: '______ is the downward transfer of authority from a manager to a subordinate',
    options: ['Centralization', 'Coordinating', 'Delegation', 'Decision making'],
    correctAnswer: 'Delegation',
  },
  {
    id: 'mgt_q216',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Which one of the following is not included in the types of management',
    options: ['Financial Management', 'Production Management', 'Personnel Management', 'Force Management'],
    correctAnswer: 'Force Management',
  },
  {
    id: 'mgt_q217',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: '______ and ______ are advantages of line organisation',
    options: ['Simplicity and quick decisions', 'Lack of specialisation and difficult to coordinate', 'Suitability and higher rejecting', 'None of the given options'],
    correctAnswer: 'Simplicity and quick decisions',
  },
  {
    id: 'mgt_q218',
    subjectId: 'management',
    topic: 'Directing and Controlling', // Decision Making
    text: '______ requires intuition and good judgment',
    options: ['Planning', 'Decision making', 'Communication', 'Controlling'],
    correctAnswer: 'Decision making',
  },
  {
    id: 'mgt_q219',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'In organisational structure, ______ is the ability to adjust, change, bend and blend without disturbing the basic structure',
    options: ['Balance', 'Stability', 'Flexibility', 'Span of control'],
    correctAnswer: 'Flexibility',
  },
  {
    id: 'mgt_q220',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts', // Production Management
    text: 'includes work analysis, planning, scheduling, routing, quality control and work study',
    options: ['Personnel Management', 'Distribution Management', 'Purchase Management', 'Production Management'],
    correctAnswer: 'Production Management',
  },
  {
    id: 'mgt_q221',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts', // Personnel Management
    text: 'Which of the following management involves selection, placement, training, transfer, safely, health for the functional area of management',
    options: ['Development management', 'Personnel management', 'Transport management', 'Purchase management'],
    correctAnswer: 'Personnel management',
  },
  {
    id: 'mgt_q222',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Supervisor has to advise troubled employee to improve his performance. Which function of management he is performing-',
    options: ['Motivation', 'Personal counseling', 'communication', 'controlling'],
    correctAnswer: 'Personal counseling',
  },
  {
    id: 'mgt_q223',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Personal Counseling is a very effective tool for troubled employee when-',
    options: ['he lost his interest in job and gives poor performance', 'he is facing personal problem', 'inferiority complex is developed', 'all above'],
    correctAnswer: 'all above',
  },
  {
    id: 'mgt_q224',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: '--- is essential because the performance of the troubled employee gets affected and also spoil the discipline of section.',
    options: ['Controlling', 'Strict monitoring', 'Personal counseling', 'Discipline'],
    correctAnswer: 'Personal counseling',
  },
  {
    id: 'mgt_q225',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Supervisor can counsel his employee by- 1. sharing worker feelings 2.understand his problem 3. giving him extra facility. 4. changing his job position',
    options: ['1&2', '2&3', '3&4', '1&4'],
    correctAnswer: '1&2',
  },
  {
    id: 'mgt_q226',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Which of the following is not a function of management?',
    options: ['Organizing', 'Controlling', 'Planning', 'Remuneration'],
    correctAnswer: 'Remuneration',
  },
  {
    id: 'mgt_q227',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: '"When employees are specialized,they become more skilled and efficient and the rate of production will increase."This refers to which principle of management of Henry Fayol?',
    options: ['Division of work', 'Remuneration', 'Initiative', 'Unity of direction'],
    correctAnswer: 'Division of work',
  },
  {
    id: 'mgt_q228',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: '"Managers should be fair in treatment towards all the employees and deal with kindness and justice."- This principle refers to:',
    options: ['Unity of command', 'Unity of direction', 'Equity of treatment', 'Scalar chain'],
    correctAnswer: 'Equity of treatment',
  },
  {
    id: 'mgt_q229',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'The management principle "Initiative" refers to :',
    options: ['fair remuneration to be paid to all employees', 'placing everything in order', 'stable and secure atmosphere', 'the necessary level of freedom provided by managers to subordinates to create and carry out plans'],
    correctAnswer: 'the necessary level of freedom provided by managers to subordinates to create and carry out plans',
  },
  {
    id: 'mgt_q230',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'The function of lower level management is:',
    options: ['to evaluate the performance of managers', 'to guide and instruct workers for day to day activities', 'to design operating policies', 'to design the organization structure'],
    correctAnswer: 'to guide and instruct workers for day to day activities',
  },
  {
    id: 'mgt_q231',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Mr.X is working as the CEO of a very prestigious company.The managerial skills which are very important to him are:',
    options: ['Technical and conceptual skills', 'Conceptual skills and human skills', 'Technical and human skills', 'Conceptual skills and controlling skills'],
    correctAnswer: 'Conceptual skills and human skills',
  },
  {
    id: 'mgt_q232',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: '"Management is the art of knowing what you want to do and then seeing that it is done in the best and cheapest way."- These are the words of :',
    options: ['Harold Koontz', 'F.W.Taylor', 'Henry Fayol', 'Mary Parker Follet'],
    correctAnswer: 'F.W.Taylor',
  },
  {
    id: 'mgt_q233',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Which of the following statements is wrong?',
    options: ['Administration relates to top level function.', 'Management is an execution function', 'Management decides what is to be done and when it is to be done .', 'Administration needs conceptual and human skills'],
    correctAnswer: 'Management decides what is to be done and when it is to be done .',
  },
  {
    id: 'mgt_q234',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Identify the person who supervises and coordinates the activities of operating employees.',
    options: ['Inspectors', 'workers', 'branch managers', 'chairman'],
    correctAnswer: 'Inspectors',
  },
  {
    id: 'mgt_q235',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: '"Selection of workers on the basis of their skills,performance standards and pay scales based on performance"- These are features of:',
    options: ['Taylor\'s principles of scientific management', 'Henry Fayol\'s principles of scientific management', 'Weber\'s Bureaucratic organization', 'general administrative theory'],
    correctAnswer: 'Taylor\'s principles of scientific management',
  },
  {
    id: 'mgt_q236',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Designing the organization system is the function of',
    options: ['Top level management', 'Middle level management', 'Lower management', 'Lower middle level management'],
    correctAnswer: 'Top level management',
  },
  {
    id: 'mgt_q237',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Monitoring day to day activities and progress is the function of:',
    options: ['Top level management', 'Middle level management', 'upper middle level management', 'Lower level management'],
    correctAnswer: 'Lower level management',
  },
  {
    id: 'mgt_q238',
    subjectId: 'management',
    topic: 'Planning and Organizing', // Staffing
    text: 'Which of the following is not a function of staffing?',
    options: ['recruitment', 'induction', 'training', 'budget'],
    correctAnswer: 'budget',
  },
  {
    id: 'mgt_q239',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Which of the following is not a type of organization?',
    options: ['line organization', 'functional organization', 'flexible organisation', 'project organization'],
    correctAnswer: 'flexible organisation',
  },
  {
    id: 'mgt_q240',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Authority always flows from:',
    options: ['superior to subordinate', 'subordinate to superior', 'both a and b', 'none of the above'],
    correctAnswer: 'superior to subordinate',
  },
  {
    id: 'mgt_q241',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'Responsibility always flows from:',
    options: ['superior to subordinate', 'subordinate to superior', 'both a and b', 'none of the above'],
    correctAnswer: 'subordinate to superior',
  },
  {
    id: 'mgt_q242',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: '______ level management give finishing touch to the plans and policies to top management',
    options: ['Middle', 'Upper middle', 'Lower', 'Operating force'],
    correctAnswer: 'Lower',
  },
  {
    id: 'mgt_q243',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'It is the first function of management',
    options: ['Planning', 'Controlling', 'Communicating', 'Capital'],
    correctAnswer: 'Planning',
  },
  {
    id: 'mgt_q244',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Position, designation, seniority defines_____',
    options: ['Centralization', 'Authority', 'Initiative', 'Scalar chain'],
    correctAnswer: 'Authority',
  },
  {
    id: 'mgt_q245',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: '_____ organisation is called as horizontal organisation',
    options: ['Line', 'Line and staff', 'Functional', 'Complex'],
    correctAnswer: 'Functional',
  },
  {
    id: 'mgt_q246',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'Middle level is ______ of management',
    options: ['Strategic level', 'Tactical level', 'Operational level', 'All of the above options'],
    correctAnswer: 'Tactical level',
  },
  {
    id: 'mgt_q247',
    subjectId: 'management',
    topic: 'Directing and Controlling',
    text: 'Which of the following is the advantage of controlling',
    options: ['Tool of the fast development', 'It reduces the elements of risk', 'Process of motivation', 'Proper utilization of resources'],
    correctAnswer: 'Proper utilization of resources',
  },
  {
    id: 'mgt_q248',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'For good working of management, ______ avoids confusion, mistakes and delays in getting the work done',
    options: ['Equity of treatment', 'Unity of direction', 'Unity of command', 'Remuneration'],
    correctAnswer: 'Unity of command',
  },
  {
    id: 'mgt_q249',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: 'According to Henri Fayol principles, manager should deal with his subordinates with kindness and justice will come under',
    options: ['Discipline', 'Equity of treatment', 'Esprit de corps', 'Initiative'],
    correctAnswer: 'Equity of treatment',
  },
  {
    id: 'mgt_q250',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: '______ refers to the relationship between people,work and resources to achieve goals',
    options: ['Actuating', 'Scheduling', 'Project', 'Organizing'],
    correctAnswer: 'Organizing',
  },
  {
    id: 'mgt_q251',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: '______ level is known as Top level management because all important decisions related to whole organization are taken by top management',
    options: ['Tactical level', 'Operational level', 'Strategic Level', 'Controlling level'],
    correctAnswer: 'Strategic Level',
  },
  {
    id: 'mgt_q252',
    subjectId: 'management',
    topic: 'Introduction to Management Concepts',
    text: '______ results into better output interns of work',
    options: ['Unity of direction', 'Division of work', 'Discipline', 'All of the above options'],
    correctAnswer: 'Division of work',
  },
  {
    id: 'mgt_q253',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'The planning process is used to prepare ______ in an organization',
    options: ['Advancement', 'Technologies', 'Discoveries', 'Budgets'],
    correctAnswer: 'Budgets',
  },
  {
    id: 'mgt_q254',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: '______ is a long term goal',
    options: ['Plan', 'Operation', 'Vision', 'Innovation'],
    correctAnswer: 'Vision',
  },
  {
    id: 'mgt_q255',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'According to M.S. Hardly accplanning is deciding in advance what is to be done. It involves the ______ from among alternatives.',
    options: ['Selection of objectives', 'Selection of Policies', 'Selection of Procedures and programmes', 'All of the Above'],
    correctAnswer: 'All of the Above',
  },
  {
    id: 'mgt_q256',
    subjectId: 'management',
    topic: 'Planning and Organizing',
    text: 'An organization is an ______',
    options: ['open system', 'close system', 'inactive system', 'none of the above'],
    correctAnswer: 'open system',
  },
];

export const getQuestionsBySubject = (subjectId: string): Question[] => {
  return questions.filter(q => q.subjectId === subjectId);
};

export const getSubjectById = (subjectId: string): Subject | undefined => {
  return subjects.find(s => s.id === subjectId);
};

// Helper function to get questions for a specific batch
export const getQuestionsForBatch = (subjectId: string, batchNumber: number, batchSize: number): Question[] => {
  const allSubjectQuestions = getQuestionsBySubject(subjectId);
  const startIndex = (batchNumber - 1) * batchSize;
  const endIndex = batchNumber * batchSize;
  return allSubjectQuestions.slice(startIndex, endIndex);
};

    
